spring:
  main:
    web-application-type: none
    banner-mode: off
  shell:
    interactive:
      enabled: true
    script:
      enabled: false
app:
  context:
    player-id:
    baseUrl: http://localhost:8080/

logging:
  level:
    ROOT: off