spring:
  application.name: api
  docker:
    compose:
      enabled: true
      file: compose.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    ROOT: info
    #org.springframework.security: DEBUG
    #org.springframework.security.web.FilterChainProxy: DEBUG
    #org.springframework.web: INFO
    #org.hibernate.orm.jdbc.bind: TRACE
    #dev.thiagooliveira: DEBUG
    #liquibase: DEBUG